#!/usr/bin/env bash
#Script that displays the content of the file /etc/passwd
while IFS= read -r line
do
    echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
root@bcc639dcfacd:/alx-system_engineering-devops/0x04-loops_conditions_and_parsing# cat 10-fizzbuzz 
#!/usr/bin/env bash
# This script displays numbers from 1 to 100.

for ((i = 1; i <= 100; i++)); do
        if ((i % 15 == 0)); then
                echo FizzBuzz
        elif ((i % 3 == 0)); then
                echo Fizz
        elif ((i % 5 == 0)); then
                echo Buzz
        else
                echo "$i"
        fi
done
